on:
  issues:
    types:
      - opened
jobs:
  new-issue:
    runs-on: ubuntu-latest
    name: New Issue
    steps:
      - name: Close/Lock/Label
        shell: bash
        run: |
          gh issue close -R ${{ github.repository }} "${{ github.event.issue.number }}" && \
          gh issue lock -R ${{ github.repository }} "${{ github.event.issue.number }}" && \
          gh issue edit -R ${{ github.repository }} --add-label "invalid" "${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ github.token }}
